[tool.poetry]
name = "smage"
version = "0.1.0"
description = "Docker image for Sagemaker"
authors = ["Hironori <stdiff@outlook.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.7"
tensorflow = "2.5.0"
transformers = "3.5.1"
altair = "^4.1.0"
pandas = "1.1.5"
numpy = "1.19.5"
matplotlib = "^3.4.2"
seaborn = "^0.11.1"
scipy = "^1.6.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
