[tool.poetry]
name = "smage"
version = "0.1.0"
description = "My custom Docker image for SageMaker"
authors = ["Hironori <stdiff@outlook.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
